### Get JWT token
POST http://localhost:8080/projectdae/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "patient1",
  "password": "1234"
}

### Who am I?
GET http://localhost:8080/projectdae/api/auth/user
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJwYXRpZW50MSIsImlzcyI6InF1aWNrc3RhcnQtand0LWlzc3VlciIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsImdyb3VwcyI6WyJQYXRpZW50Il0sImV4cCI6MTY0MDgwOTEyNX0.auGcRyy6R8J2croI2xbt9xJQvSiHBdqHrIfxwYPdhi_qqxd1mHvTvuh8Zd_xyUKfvArhgi3CzNZdKAHWrh8pIBqiEpX2wNIKJi0zz7wMElBMTca5Q736X3lqTGurXgtaeOb9pvixsm-nCTqnfINFyG_NvykFaf_HeMm2g1wxuADaZr3A8xiTRLSKMYZ8bBtL4FSDLtKi3mNpA3kBKXsDQS8bBqhe6j7JuQsMvFGyQCpxvC5NdZdv6YlCLwb7SqnOfge-JWsYBh4ryVCAELhBfDseNJWwQDyRPB7BChaHdhTqwlBlE5kQJRBc1CdsmYOySNvIatCx7JEdrxQAWesqbw

##### Get patients list
GET http://localhost:8080/projectdae/api/patients
Accept: application/json
Authorization: "eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJwYXRpZW50MSIsImlzcyI6InF1aWNrc3RhcnQtand0LWlzc3VlciIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsImdyb3VwcyI6WyJQYXRpZW50Il0sImV4cCI6MTY0MDc1NzAyNH0.dXB4jmosbDbux1zWwJQ8n7OZDAcoE1Bk0WmmGcSOGaf_G03CNi1cNJU47Mby0KtCvK2UvO9orMcA3lDg2cucEk2itS5K0Jk-8WaITMJS07RDk3X5FtM0nXkMG-slGCvs5gCXjwQaZLKGltmkjLmI6j2eW8OP33D_NyHuGuVtvQe10smBqQ8PdGnpfK1s5Vi0_NhOD2gPcK38TrFv_7gJ3XXHVuQ3dDUJcHMtsRNkMav0Nse18RfF7kfBr1GWKaFy_kWmFNcRxzIQ4adLKl-DlIxG6JRoQWxnbJKsGu6RuJZYfLUS71AS3YVJ7ckekVHkoHstTy9W4tBr40JLlkA5_g"

### Create new patient
POST http://localhost:8080/projectdae/api/patients
Content-Type: application/json
Authorization: Bearer replace this with generated JWT token
{
"email": "jane@mail.com",
 "name": "Jane Doe",
 "username": "1234567",
 "password": "aaaaa"
}
### Enroll patient in a subject - run after the previous POST
PUT http://localhost:8080/projectdae/api/patients/1234567/subjects/enroll/1
Authorization: Bearer replace this with generated JWT token
### Get a patient’s details
GET http://localhost:8080/projectdae/api/patients/1111111
Accept: application/json
Authorization: Bearer replace this with generated JWT token
### Delete a patient - run after the previous POST
DELETE http://localhost:8080/projectdae/api/patients/1234567
Accept: application/json
Authorization: Bearer replace this with generated JWT token
###