##### MeasureType
GET http://localhost:8080/projectdae/api/measureTypes/
Accept: application/json


###
GET http://localhost:8080/projectdae/api/qualitativeMeasureTypes/
Accept: application/json
###
POST http://localhost:8080/projectdae/api/qualitativeMeasureTypes
Content-Type: application/json

{
  "name": "test",
  "multiple": 0,
  "min": 1,
  "max": 2,
  "decimal": 0
}
###1
PUT http://localhost:8080/projectdae/api/qualitativeMeasureTypes/1
Content-Type: application/json

{
  "name": "Temperature",
  "multiple": 1,
  "min": 2,
  "max": 99,
  "decimal": 0
}