##### Patients ---------------------------------------------------------------------
GET http://localhost:8080/projectdae/api/patients/
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDEyNzg0MzZ9.A_ftBiPhbmFzEmWhaEqsufaAO6CBUrD_5HI5q0XcVFYz_HDTDGrwUo4VX9zYRMgPSGf0_M0MPxLW85eiwMEBMwbA_2QT21miVI_YfTLP3guzcDNXGFdIszUNhfQsGDRGYuMCS6CAx4XprD5irXf6jWX17z9dYzfGqWIWUF8WZZSVLzXMwIZDSwhbmch94ezcsEtb3roSisChwqVv5Aa4wODr-tj1sz2IQ9HGQ9plZYS_2WdBtzw-NYc19sMkqZgFCwFF9ZAfaSOzyz2Eu8v3GGl6lctZAniJzHKQJCjb3cNMQC_3nXPA2TTQ6NJqZZIAG2ZsfNJlEbxGaJIt4DTOBA
Accept: application/json
##### Patients/active
GET http://localhost:8080/projectdae/api/patients/active/patient1
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDExNDMzMzN9.WziKSc14Ji6G5XU0E3l4WATiOAJRKoKVcpq60BncgpZclk6E1nzWiqzwt8BQOoWTq1ptvWtaanZTSjXBQaCiSPjYEum0IbN_p7wPouqnH6n2LUTLMQEF_mvfIuuYfL4pOTR6IksF-Cpr5W9Yv-wCQMd0Y20N6GtEHQxirHESyFXuzVUQS4KjhNIrjXmHk0IDjG9o09tIufyS2HjDck9sQtyErAUkhZwjU90793R7U5KODEKZ1Z2pafHcvLg24jvmEZxevfbFe3U7j-8loDzFcikCDGxn1rjamQ8Pm8Z_DJwVtbIYcZ_BYHzVMyZ1Kmn-nGMPcbNeYpLyaNYyNIRZhw
Accept: application/json
###
DELETE http://localhost:8080/projectdae/api/patients/patient1
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDExNDMzMzN9.WziKSc14Ji6G5XU0E3l4WATiOAJRKoKVcpq60BncgpZclk6E1nzWiqzwt8BQOoWTq1ptvWtaanZTSjXBQaCiSPjYEum0IbN_p7wPouqnH6n2LUTLMQEF_mvfIuuYfL4pOTR6IksF-Cpr5W9Yv-wCQMd0Y20N6GtEHQxirHESyFXuzVUQS4KjhNIrjXmHk0IDjG9o09tIufyS2HjDck9sQtyErAUkhZwjU90793R7U5KODEKZ1Z2pafHcvLg24jvmEZxevfbFe3U7j-8loDzFcikCDGxn1rjamQ8Pm8Z_DJwVtbIYcZ_BYHzVMyZ1Kmn-nGMPcbNeYpLyaNYyNIRZhw
Accept: application/json
###
POST http://localhost:8080/projectdae/api/patients
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDEyODAzODd9.aLsv9wQr0TH0A7hUYTAXTB7k2lnV9E0iebeyxsXGOjVx0pvU_rgiJIY88VmH6tsIi2JVCbBD9ZMhb8a5Z2voeodWedO8W99JwKQ7tlJeTVCLVGxCyjx-UlmO_YUAieA4HPlZMhUnjbtAsOruD8LFTPQY2mJr3-IUb9qWnKLh_OIrDW59--yiyxMRby5qPF3QIQQkv6CtJayAi0l5hIZYpBjbbTO_Ofxak7ixjKYfrTjWgISJWNwxxoSyQdggMkce9A6uzVvuKmQlbpfxoxJeuQq6z_Zzp_vihX4qIWbZLLNBvUxAwOl1Ji5MOAl4l1piSjnE81YWRSPWCIwAU3dO2A

{
  "email": "patient8@mail.com",
  "name": "patient8",
  "username": "patient8",
  "password": "1234",
  "role": "Patient"

}
###
PUT http://localhost:8080/projectdae/api/patients/patient1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDA4MjY4MTR9.VWV5660fbchiqCezPczhz0Ozwv4FeR394kTJdgK5bpByIrUzeA_LoI0F_yIfWaa9rigVSdEpeRYgFZKw401fo7hqVb78bqCgBMsL2dUeUFbarhV3LN0GlSGuR6Dc3NKEk8b7ry-wr413AOYzm5kNBlWh4eg8P1TbX4MjnLy5pJODFKBKZwhc2v-TA5SPF9NV82GA5ybPSxrbXqynR4ykCp_2NzYqC5I9O0Iom21-bshbzGpNzRN4h0zMd8FafqZwAyl4jEyhLcSTesqTZK9E7fy8GXUl6ggnacDl30eIP1YReXw83cbkOLM4EgjBLljOd2ETRHoe8LmgpRJbVgj8Nw

{
  "email": "manel@mail.com",
  "name": "manel",
  "username": "patient1",
  "password": "1234",
  "role": "Patient"

}

###
PUT http://localhost:8080/projectdae/api/patients/patient8/updatePassword
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDEyODAzODd9.aLsv9wQr0TH0A7hUYTAXTB7k2lnV9E0iebeyxsXGOjVx0pvU_rgiJIY88VmH6tsIi2JVCbBD9ZMhb8a5Z2voeodWedO8W99JwKQ7tlJeTVCLVGxCyjx-UlmO_YUAieA4HPlZMhUnjbtAsOruD8LFTPQY2mJr3-IUb9qWnKLh_OIrDW59--yiyxMRby5qPF3QIQQkv6CtJayAi0l5hIZYpBjbbTO_Ofxak7ixjKYfrTjWgISJWNwxxoSyQdggMkce9A6uzVvuKmQlbpfxoxJeuQq6z_Zzp_vihX4qIWbZLLNBvUxAwOl1Ji5MOAl4l1piSjnE81YWRSPWCIwAU3dO2A

{
  "token": "[B@2c167309",
  "password": "novapass"
}




###### HealthProfessionals ------------------------------------------------------------------------------------

POST http://localhost:8080/projectdae/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "admin1",
  "password": "1234"
}
###

GET localhost:8080/projectdae/api/healthProfessionals
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDExNDY3NjR9.JSuKCiWSBtLLHcJngaPYqsdLInzLTQmYDq6pP-yIEDngrqXdy3VZreoNIiv10_9C8WRo_2sweJUSx6d9OMTXmrVN0o92bYIQWbHK2-6QA9z1c5FdEVLisa1RszzXPXnfdQY_Ama8cPM6Cab9VgXXKpT0E2ULngswd_jL6t7Lrtv-rqXeIarWm0sY3wxvz3TWuE6XYGtFsxhacSTSlMOp17xxe3acnGUSSW-XfRVcNCAL3KuN5TrgnDVAXxdPoKUXBwT5It9ErWq1Bl-mc4jlt1i5QYVy8blVe4xnTvvRqduWzlmeD4wOc2yCsvOG_jxrlzjyu_IF_Cvccyyfmcu_bw
###
GET localhost:8080/projectdae/api/healthProfessionals/professionalTeste
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDA5MTgwMjh9.YyQCxTzjTTRVrKWq6bb1hNLCTjNsjww9gKkPaSMmoyvSmFWnZ52C8CMoaaE8RWBF_MXAd7q2YapngScFIyWJZZL8mHcS870KqqB_d-pdLM4-KFxtvtQnwAg8Tvg8XKimd1gOOJxoeMZHsl3GpAYqyrrykptoRtTJApOIUrA-yUyW0bLOq3TquWubCU-jqT6oTmUADdXXHFFXZh0FBlC4R7xrM0z0dX-9uzHiH1Hj7pJRs39PHWIfo3i2T7kcKxIycXxDQQr0DiYdOKXvLcDTCw5eb1Jl94lWpSaHUhM75Mbb3f6J8P69eyXTu6ElbL7Rx0JF1TTja_-UCyz_zyDTqw
###
POST http://localhost:8080/projectdae/api/healthProfessionals
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDEzMjE2Nzh9.KeuIFQLjcfP8t2QOUu2EKIrDM1UQkxx8DdfwZoacCguj3ZD8Fo78ju8vD5mfnzcwTsMZfnQN5kkPUNSAFtw2oIvf5_KwYKh6pXrzo95rp0dxgnnTzikut48lqBs7iaQhVv83I5Z7ervfMFA91W9zjhvw5p6V3x2iyUGQuLqCzyINjF17qASuLjhovaKS6UgjeDGbd-NhPTudAwWDYkCQJcIVZFm_q_52al2D7W-laDHLEQf3ugLB70fxLpEcAeJzU9vqcsPAp4HQS57Uv8lN3pchcgJTll6JwEJ5ae82A--AmTlVqjP90aqqyV_u2v5yOIJdQ6On18FgXQ18Ss4r3A

{
  "username": "professionalTeste4",
  "password": "1234",
  "name": "professionalTeste4",
  "email": "professionalTeste4@mail.com",
  "version":  0,
  "profession": "Doctor",
  "chefe": false,
  "role": "HealthProfessional"
}

###
PUT http://localhost:8080/projectdae/api/healthProfessionals/professional1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDA5MTgwMjh9.YyQCxTzjTTRVrKWq6bb1hNLCTjNsjww9gKkPaSMmoyvSmFWnZ52C8CMoaaE8RWBF_MXAd7q2YapngScFIyWJZZL8mHcS870KqqB_d-pdLM4-KFxtvtQnwAg8Tvg8XKimd1gOOJxoeMZHsl3GpAYqyrrykptoRtTJApOIUrA-yUyW0bLOq3TquWubCU-jqT6oTmUADdXXHFFXZh0FBlC4R7xrM0z0dX-9uzHiH1Hj7pJRs39PHWIfo3i2T7kcKxIycXxDQQr0DiYdOKXvLcDTCw5eb1Jl94lWpSaHUhM75Mbb3f6J8P69eyXTu6ElbL7Rx0JF1TTja_-UCyz_zyDTqw

{
  "password": "1234",
  "name": "ManuelTeste1",
  "email": "professionalTeste@mail.com",
  "version":  0,
  "profession": "Doctor",
  "chefe": false,
  "role": "HealthProfessional"

}

###

PUT http://localhost:8080/projectdae/api/healthProfessionals/professionalTeste4/updatePassword
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDEzMjE2Nzh9.KeuIFQLjcfP8t2QOUu2EKIrDM1UQkxx8DdfwZoacCguj3ZD8Fo78ju8vD5mfnzcwTsMZfnQN5kkPUNSAFtw2oIvf5_KwYKh6pXrzo95rp0dxgnnTzikut48lqBs7iaQhVv83I5Z7ervfMFA91W9zjhvw5p6V3x2iyUGQuLqCzyINjF17qASuLjhovaKS6UgjeDGbd-NhPTudAwWDYkCQJcIVZFm_q_52al2D7W-laDHLEQf3ugLB70fxLpEcAeJzU9vqcsPAp4HQS57Uv8lN3pchcgJTll6JwEJ5ae82A--AmTlVqjP90aqqyV_u2v5yOIJdQ6On18FgXQ18Ss4r3A

{
"token": "[B@1806fe51",
"password": "novapass"
}
###
DELETE http://localhost:8080/projectdae/api/healthProfessionals/professional1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDExNDY3NjR9.JSuKCiWSBtLLHcJngaPYqsdLInzLTQmYDq6pP-yIEDngrqXdy3VZreoNIiv10_9C8WRo_2sweJUSx6d9OMTXmrVN0o92bYIQWbHK2-6QA9z1c5FdEVLisa1RszzXPXnfdQY_Ama8cPM6Cab9VgXXKpT0E2ULngswd_jL6t7Lrtv-rqXeIarWm0sY3wxvz3TWuE6XYGtFsxhacSTSlMOp17xxe3acnGUSSW-XfRVcNCAL3KuN5TrgnDVAXxdPoKUXBwT5It9ErWq1Bl-mc4jlt1i5QYVy8blVe4xnTvvRqduWzlmeD4wOc2yCsvOG_jxrlzjyu_IF_Cvccyyfmcu_bw




###### Admins------------------------------------------------------------------------------------------------------------------------------
GET localhost:8080/projectdae/api/administrators
###
GET localhost:8080/projectdae/api/administrators/admin1
###
POST localhost:8080/projectdae/api/administrators
Content-Type: application/json

{
  "email": "AdminTestePost@mail.com",
  "name": "AdminTestePost",
  "username": "AdminTestePost",
  "password": "1234",
  "role": "Admin"
}
###
PUT http://localhost:8080/projectdae/api/administrators/admin1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDA5Mjc0MzF9.cDC8FaM4Eysmx43C-UaMHdkUNtpDH7jkQbjAcYXjLwIVVkFZ9yvtsed1gueSQQsZZbxE0mPb0p1PsdvLGxEfniRK8DvtBQPeqyOhYZASiTNAu2khrDlVtRy6ZTb0g1r1JP3XG2gV-WnSwZQ-7MSdcBmAop3IW16VPJ4Ah14h3TlBco6tF8L0LoJGMKzMpJWayDC-buZgfYYtJxsUDkZGphEkt9TdwUBDQBOkdKvB_8np5EgdnPBh1S4AuN-dRgJYVVLMc4zFD0N1Xk3wBs-kl9h6WUYi-8HBerwFBX7dXTIIV1nvxVMTuvbICC7B5u_bCgwFLsEHHCvfY5clb5xSlw

{
  "name": "goncaloteste",
  "email": "admin@mail.com",
  "version":  1

}

##### USERS
##Get all users
GET localhost:8080/projectdae/api/Users
